import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:smart_money_tracker/core/models/budget_model.dart';
import 'package:smart_money_tracker/core/models/budget_instance_model.dart';
import 'package:smart_money_tracker/core/services/time_service.dart';
import 'package:smart_money_tracker/core/services/local_database_helper.dart';

class BudgetRepository {
  final LocalDatabaseHelper _dbHelper = LocalDatabaseHelper.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  Future<void> saveBudget(
    String uid,
    BudgetModel budget, {
    BudgetInstanceModel? initialInstance,
  }) async {
    // Save parent to local SQLite
    await _dbHelper.saveBudget(uid, budget);

    if (initialInstance != null) {
      await _dbHelper.saveBudgetInstance(uid, initialInstance);
    }

    // Sync parent and optional initial instance to Firebase
    try {
      final batch = _firestore.batch();
      final budgetDocRef = _firestore
          .collection('users')
          .doc(uid)
          .collection('budgets')
          .doc(budget.id);

      batch.set(
        budgetDocRef,
        {
          'id': budget.id,
          'name': budget.name,
          'categoryId': budget.categoryId,
          'subcategoryId': budget.subcategoryId,
          'amount': budget.amount,
          'period': budget.period.name,
          if (budget.startDate != null)
            'startDate': budget.startDate!.toIso8601String(),
          if (budget.endDate != null)
            'endDate': budget.endDate!.toIso8601String(),
          'isStopped': budget.isStopped,
          'isRecurring': budget.isRecurring,
          'createdAt': budget.createdAt.toIso8601String(),
        },
        SetOptions(merge: true),
      );

      if (initialInstance != null) {
        final instanceDocRef = budgetDocRef
            .collection('recurring')
            .doc(initialInstance.id);
        batch.set(
          instanceDocRef,
          initialInstance.toMap(),
          SetOptions(merge: true),
        );
      }

      await batch.commit();
    } catch (e) {
      print('Error saving budget to Firebase: $e');
    }
  }

  Future<void> saveBudgetInstance(
    String uid,
    BudgetInstanceModel instance,
  ) async {
    await _dbHelper.saveBudgetInstance(uid, instance);

    try {
      await _firestore
          .collection('users')
          .doc(uid)
          .collection('budgets')
          .doc(instance.budgetId)
          .collection('recurring')
          .doc(instance.id)
          .set(instance.toMap(), SetOptions(merge: true));
    } catch (e) {
      print('Error saving budget instance to Firebase: $e');
    }
  }

  Future<List<BudgetModel>> getBudgets(String uid) async {
    return await _dbHelper.getBudgets(uid);
  }

  Future<List<BudgetInstanceModel>> getBudgetInstances(
    String uid, {
    String? budgetId,
  }) async {
    return await _dbHelper.getBudgetInstances(uid, budgetId: budgetId);
  }

  Future<void> deleteBudgetInstance(
    String uid,
    String budgetId,
    String instanceId,
  ) async {
    await _dbHelper.deleteBudgetInstance(uid, instanceId);

    try {
      await _firestore
          .collection('users')
          .doc(uid)
          .collection('budgets')
          .doc(budgetId)
          .collection('recurring')
          .doc(instanceId)
          .delete();
    } catch (e) {
      print('Error deleting budget instance from Firebase: $e');
    }
  }

  Future<void> deleteBudget(String uid, String id) async {
    // Delete locally (cascades and deletes instances from SQLite)
    await _dbHelper.deleteBudget(uid, id);

    // Delete from Firebase
    try {
      // 1. Delete all instances in subcollection
      final subcollectionSnapshot = await _firestore
          .collection('users')
          .doc(uid)
          .collection('budgets')
          .doc(id)
          .collection('recurring')
          .get();

      final batch = _firestore.batch();
      for (var doc in subcollectionSnapshot.docs) {
        batch.delete(doc.reference);
      }

      // 2. Delete parent budget doc
      batch.delete(
        _firestore
            .collection('users')
            .doc(uid)
            .collection('budgets')
            .doc(id),
      );

      await batch.commit();
    } catch (e) {
      print('Error deleting budget from Firebase: $e');
    }
  }

  Future<void> syncBudgetsFromFirebase(String uid) async {
    try {
      final snapshot = await _firestore
          .collection('users')
          .doc(uid)
          .collection('budgets')
          .get()
          .timeout(const Duration(seconds: 10));

      if (snapshot.docs.isEmpty) return;

      final budgetsToSave = <BudgetModel>[];
      final instancesToSave = <BudgetInstanceModel>[];

      final results = await Future.wait(
        snapshot.docs.map((doc) async {
          final data = doc.data();

          final rawName = (data['name'] as String?)?.trim() ?? '';
          final bool isAutoGeneratedName = rawName == 'Budget' ||
              rawName == 'Category Budget' ||
              rawName == 'Overall Budget' ||
              (rawName.isNotEmpty && rawName.endsWith(' Budget'));

          final budget = BudgetModel(
            id: data['id'] ?? doc.id,
            name: isAutoGeneratedName ? '' : rawName,
            categoryId: data['categoryId'],
            subcategoryId: data['subcategoryId'],
            amount: (data['amount'] as num).toDouble(),
            period: BudgetPeriod.values.firstWhere(
              (e) => e.name == data['period'],
              orElse: () => BudgetPeriod.monthly,
            ),
            startDate: data['startDate'] != null
                ? DateTime.parse(data['startDate'])
                : null,
            endDate: data['endDate'] != null
                ? DateTime.parse(data['endDate'])
                : null,
            isStopped: data['isStopped'] ?? false,
            isRecurring: data['isRecurring'] ?? true,
            createdAt: data['createdAt'] != null
                ? DateTime.parse(data['createdAt'])
                : TimeService.now(),
          );

          final docInstances = <BudgetInstanceModel>[];
          if (budget.isRecurring) {
            try {
              final instancesSnapshot = await doc.reference
                  .collection('recurring')
                  .get()
                  .timeout(const Duration(seconds: 10));

              final instances = instancesSnapshot.docs
                  .map((instDoc) => BudgetInstanceModel.fromMap(instDoc.data()))
                  .toList();
              docInstances.addAll(instances);
            } catch (e) {
              print('Error fetching recurring instances for budget ${budget.id}: $e');
            }
          }

          return (budget: budget, instances: docInstances);
        }),
      );

      for (var result in results) {
        budgetsToSave.add(result.budget);
        if (result.instances.isNotEmpty) {
          instancesToSave.addAll(result.instances);
        }
      }

      if (budgetsToSave.isNotEmpty) {
        await _dbHelper.saveBudgets(uid, budgetsToSave);
      }
      if (instancesToSave.isNotEmpty) {
        await _dbHelper.saveBudgetInstances(uid, instancesToSave);
      }
    } catch (e) {
      print('Error syncing budgets from Firebase: $e');
    }
  }

  Stream<void> get onBudgetsChanged => _dbHelper.onChange;
}

